# 该配置为反向连接示例
server:
  port: 8089

shiro:
  ws:
    server:
      enable: true
      url: "/ws/demo"
  plugin-list:
    - com.akaxedx.newqqbot.plugins.DingPlugin
#mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 121805
    username: root
    #这里要更改数据库只需要更改voredb那个地方就可以了
    url: jdbc:mysql://154.64.254.59:3306/new_bot?&useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
