# 该配置为反向连接示例
server:
  port: 8089

shiro:
  ws:
    server:
      enable: true
      url: "/ws/demo"
  plugin-list:
    - com.akaxedx.newqqbot.plugins.AtPlugin
    - com.akaxedx.newqqbot.plugins.LolPlugin
    - com.akaxedx.newqqbot.plugins.RssPlugin
    - com.akaxedx.newqqbot.plugins.SJZPlugin
#mysql配置
blog:
  host: "你的host"
  http-port: "3000"
  blog-addr: "域名"
coze:
  key: "key"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: QkjZPG37CzckKKiw
    username: qq_bot
    url: jdbc:mysql://localhost:3306/qq_bot?&useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
